//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Pacjenta
    {
        public int PacjentID { get; set; }
        public Nullable<bool> Odra { get; set; }
        public Nullable<bool> Swinka { get; set; }
        public Nullable<bool> Rozyczka { get; set; }
    
        public virtual Pacjent Pacjent { get; set; }
    }
}
