//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlinikaEntities : DbContext
    {
        public KlinikaEntities()
            : base("name=KlinikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<Historia_Pacjenta> Historia_Pacjenta { get; set; }
        public virtual DbSet<Leczenie> Leczenie { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<Recepta> Recepta { get; set; }
        public virtual DbSet<Skierowanie> Skierowanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ubezpieczenie_Pacjenta> Ubezpieczenie_Pacjenta { get; set; }
        public virtual DbSet<Wizyta> Wizyta { get; set; }
        public virtual DbSet<Zaopatrzenie> Zaopatrzenie { get; set; }
        public virtual DbSet<Zuzycie_Lekow> Zuzycie_Lekow { get; set; }
    }
}
