//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubezpieczenie_Pacjenta
    {
        public int PacjentID { get; set; }
        public string Zawod { get; set; }
        public string Pracodawca { get; set; }
        public string AdresPracodawcy { get; set; }
        public string NrTelefonuPracodawcy { get; set; }
        public string StatusUbezpieczenia { get; set; }
        public Nullable<int> NrUbezpieczenia { get; set; }
    
        public virtual Pacjent Pacjent { get; set; }
    }
}
