//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zuzycie_Lekow
    {
        public int WizytaID { get; set; }
        public int ZaopatrzenieID { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Wizyta Wizyta { get; set; }
        public virtual Zaopatrzenie Zaopatrzenie { get; set; }
    }
}
